# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-20 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rates_diagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates_all',
            name='ask',
            field=models.IntegerField(default=0),
        ),
    ]
